### PR TITLE
fix: `randomuser` not getting offline users by default

### LINKED ISSUE #234: `$randomuser` only chooses from cached users
It would be really useful if randomuser could pick offline users as well as online ones.
I was told using $ruser would allow that, but it does not work on my server.
I was then told fetchall had to be turned on by a moderator for this to work so I was wondering if that could be possible.
Thanks.

### PR DESCRIPTION
**Pull request by Skillz4Killz**
### Items Changed

- [x] Commands
- [ ] Events
- [ ] Handlers
- [ ] Structures
- [ ] Tasks
- [ ] Documentation
- [ ] Other: ______

### Description

This PR allows getting offline users when doing `$randomuser`. The issue was that the args variable was ALWAYS an array this became truthy and therefore passed for the first in the ternary. Regexes are best avoided when possible to do it in easier ways imo.

### Issues

Closes #234 

### Have You...?

- [x] I have read the [Contributing Guidelines](https://github.com/typicalbot/typicalbot/blob/master/.github/CONTRIBUTING.md).
- [x] I have completed the [pull request template](https://github.com/typicalbot/typicalbot/blob/master/.github/PULL_REQUEST_TEMPLATE.md).
- [x] I have checked open [pull requests](https://github.com/typicalbot/typicalbot/pulls) for upcoming features and fixes.

### CODE REVIEW

File: src/commands/utility/randomuser.ts [hunk 1]
```diff
@@ -2,22 +2,19 @@ import Command from '../../lib/structures/Command';
...
-        const args = regex.exec(parameters);
         const role = parameters
             ? message.guild.roles.cache.get(parameters)
                 || message.guild.roles.cache.find((role) => role.name.toLowerCase() === parameters.toLowerCase())
             : message.mentions.roles.first();
 
         const members = role
             ? role.members.filter((m) => !m.user.bot)
-            : args
+            : ['-o', '-online'].includes(parameters)
```
Comment (tjrgg) [inline src/commands/utility/randomuser.ts:17]: What about `-o` and `--online`? Just a thought.

Comment (Skillz4Killz) [reply src/commands/utility/randomuser.ts:17]: -o will work. Do you want to add --online as an acceptable answer? What are the acceptable args you want to accept for this?

Comment (nsylke) [reply src/commands/utility/randomuser.ts:17]: no, `-o` and `-online` are the only acceptable args - according to the regex

**Review by nsylke — APPROVED** [review]

File: src/commands/utility/randomuser.ts (hunk 1 above)
Comment (tjrgg) [reply src/commands/utility/randomuser.ts:17]: I know. I'm purposing to change it. Could also add `-r` and `--role` for the role argument.

Comment (nsylke) [reply src/commands/utility/randomuser.ts:17]: Should be a separate issue/pr

Comment (tjrgg) [reply src/commands/utility/randomuser.ts:17]: A separate PR would make this one redundant.

Comment (nsylke) [reply src/commands/utility/randomuser.ts:17]: `-r` and `-role` would not be a fix.

Comment (tjrgg) [reply src/commands/utility/randomuser.ts:17]: Can be changed.

Comment (Skillz4Killz) [reply src/commands/utility/randomuser.ts:17]: Note the role argument requires a role being provided. If it's just -r or -role i don't think that adds anything beneficial or did i misunderstand the request

Comment (tjrgg) [reply src/commands/utility/randomuser.ts:17]: To be clear, I don't like `-r` and `-role`. I prefer the CLI standard of one dash for shorthand, two dashes for longhand (hence, `-r` and `--role`).

With regard to `-r`, that would prefix the role argument (e.g. -r VIP), a CLI type of output.

I suppose this could be part of a greater effort to make arguments more consistent.

Comment (Skillz4Killz) [reply src/commands/utility/randomuser.ts:17]: TBH i'm confused why any flags like this are even wanted. Are you sure about this? CLI standards are built with developers in mind. A bot isn't made for devs but average end-users. I'm not sure if this would be a helpful change to user experience but a harmful one.

99% of users are used to do doing
`$mute @user reason`
Having them do 
`$mute --user=@user --reason="my reason"` 
Seems worse to me

Comment (tjrgg) [reply src/commands/utility/randomuser.ts:17]: I'm okay with that, I just want to see it be consistent with everything else.

**Review by Androz2091 — APPROVED** [review]

**Comment by Androz2091** [comment]
Sorry, I didn't want to add a review 😅
